version: 0.2

phases:
  
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $DOCKERHUB_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION .
  post_build:
    commands:
      - echo Pushing Docker images to Docker Hub...
      - docker push $DOCKERHUB_REPO:latest
artifacts:
  files: output/imagedefinitions.json
#   #hopefully works
#Artificats