version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $DOCKERHUB_REPO:latest .
      - echo '[{"name":"mkconatiner","imageUri":"'$DOCKERHUB_REPO:latest'"}]' > imagedefinitions.json
      - cat imagedefinitions.json
      - |
        echo '{
          "AWSEBDockerrunVersion": 2,
          "containerDefinitions": [
            {
              "name": "your-container-name",
              "image": "'"$DOCKERHUB_REPO:latest"'",
              "essential": true,
              "memory": 128,
              "portMappings": [
                {
                  "hostPort": 80,
                  "containerPort": 80
                }
              ]
            }
          ]
        }' > Dockerrun.aws.json
      - cat Dockerrun.aws.json
      # Rest of your build commands
  post_build:
    commands:
      - echo Pushing Docker images to Docker Hub...
      - docker push $DOCKERHUB_REPO:latest
artifacts:
  files: Dockerrun.aws.json
# Commit -> Build -> Store -> Deploy